- name: Install packages required to add repositories
  become: true
  ansible.builtin.apt:
    state: present
    install_recommends: false
    update_cache: true
    pkg:
      - bridge-utils
      - ca-certificates
      - curl
      - gnupg
      - wget

- name: Get system architecture
  ansible.builtin.command: dpkg --print-architecture
  register: deb_architecture
  become: true
  changed_when: false

- name: Ensure apt keyrings directory exists
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download Docker GPG key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
    force: true

- name: Add Docker apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: >
      deb [arch={{ deb_architecture.stdout }}
      signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/debian
      {{ ansible_distribution_release }} stable
    state: present
    filename: docker
    update_cache: true

- name: Download GitHub CLI GPG key
  become: true
  ansible.builtin.get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /etc/apt/keyrings/githubcli-archive-keyring.gpg
    mode: "0644"
    force: true

- name: Add GitHub CLI apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: >
      deb [arch={{ deb_architecture.stdout }}
      signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg]
      https://cli.github.com/packages stable main
    state: present
    filename: github-cli
    update_cache: true
