- name: Install packages to add docker repository
  become: true
  ansible.builtin.apt:
    state: present
    install_recommends: false
    pkg: "{{ item }}"
    update_cache: true
  loop:
    - bridge-utils
    - ca-certificates
    - curl
    - gnupg

- name: Get architecture
  ansible.builtin.command: dpkg --print-architecture
  register: deb_architecture
  changed_when: false

- name: Get gpg key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
    force: true

- name: Add docker apt repository key.
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: "0644"
    force: true

- name: Add docker apt repository.
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    update_cache: true
    filename: docker
