- name: instal packages
  become: true
  apt:
    state: present
    install_recommends: false
    pkg:
      - bridge-utils
      - ca-certificates
      - curl
      - gnupg
    update_cache: true

- name: get architecture
  shell: dpkg --print-architecture
  register: deb_architecture

- name: get gpg key
  become: true
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: 0644
    force: true
  tags: install_docker

- name: add docker apt repository key.
  become: true
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: 0644
    force: true
  tags: install_docker

- name: add docker apt repository.
  become: true
  apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
    filename: docker
  tags: install_docker

- name: install docker and related components
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: true
  tags: install_docker

- name: restart Docker
  systemd:
    name: docker
    state: restarted
    masked: false
  tags: install_docker
