# Install yay AUR helper
- name: Install yay AUR helper
  become: true
  ansible.builtin.shell: |
    sudo pacman -S --needed git base-devel
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -si --noconfirm
  args:
    creates: "/usr/bin/yay"
