- name: Install yay AUR helper (if on Arch)
  ansible.builtin.include_tasks: tasks/aur.yml
  when: "ansible_pkg_mgr == 'pacman'"

- name: Install wlogout on arch
  changed_when: false
  ansible.builtin.command: yay -S wlogout --noconfirm
  when: "ansible_pkg_mgr == 'pacman'"

- name: Enable Copr repository
  become: true
  ansible.builtin.command: dnf copr enable -y erikreider/SwayNotificationCenter
  when: ansible_pkg_mgr == 'dnf'
  changed_when: true

- name: Install docker on apt based systems
  ansible.builtin.include_tasks: tasks/apt-docker.yml
  when: "ansible_pkg_mgr == 'apt'"

