- name: Git personal setup email
  community.general.git_config:
    name: user.email
    scope: global
    value: "arnevanmaele@gmail.com"

- name: Git personal setup name
  community.general.git_config:
    name: user.name
    scope: global
    value: "arnevm123"
