- name: Check if bob is installed
  changed_when: false
  ansible.builtin.command: "{{ ansible_env.HOME }}/.cargo/bin/bob --version"
  register: bob_exists
  ignore_errors: true

- name: Install bob
  when: bob_exists is failed
  changed_when: false
  ansible.builtin.command: "{{ ansible_env.HOME }}/.cargo/bin/cargo install wl-gammarelay-rs --locked"

- name: Install bob
  when: bob_exists is failed
  changed_when: false
  ansible.builtin.command: "{{ ansible_env.HOME }}/.cargo/bin/cargo install bob-nvim"

- name: Install tatum
  when: bob_exists is failed
  changed_when: false
  ansible.builtin.command: "{{ ansible_env.HOME }}/.cargo/bin/cargo install --git https://github.com/elijah-potter/tatum --locked"
