- name: Install Golang
  ansible.builtin.command:
    cmd: ./install-go.sh
    chdir: "{{ user_home }}/bin"
    creates: "{{ user_home }}/go/bin"

- name: Install GolangCi-lint
  become: true
  ansible.builtin.command:
    cmd: ./install-golangci.sh
    chdir: "{{ user_home }}/bin"
    creates: "{{ user_home }}/.gopath/bin/golangci-lint"
